trigger: none
pr:
  branches:
    include:
    - feature/*
  paths:
    include:
    - deploy/terraform/run/sap_landscape/*
    - deploy/terraform/terraform-units/modules/sap_landscape/*
variables:
  - group: azure-config-variables
  - group: azure-sap-hana-pipeline-secrets
  - template: templates/variables.yaml
stages:
- stage:
  pool:
    vmImage: "ubuntu-18.04"
  variables:
    ssh_timeout_s: 120
  jobs:
  - job: createSAPLandscape
    steps:
      - template: templates/util/prepare-agent.yml
      - template: templates/util/collect-deployer-info.yml
        parameters:
          deployer_env: "UNIT"
      - template: templates/util/add-agent-to-deployer-nsg.yml
        parameters:
          deployer_env: "UNIT"
      - template: templates/saplandscape/create-saplandscape-steps.yml
        parameters:
          branch_name: $(targetBranchName)
          deployer_env: "UNIT"
          saplib_env: "UNIT"
          saplandscape_env: "$(Build.BuildId)"
      - template: templates/saplandscape/validate-saplandscape-steps.yml
        parameters:
          branch_name: $(sourceBranchName)
          saplandscape_env: "$(Build.BuildId)"
      - template: templates/saplandscape/create-saplandscape-steps.yml
        parameters:
          branch_name: $(sourceBranchName)
          deployer_env: "UNIT"
          saplib_env: "UNIT"
          saplandscape_env: "$(Build.BuildId)"
      - template: templates/util/remove-agent-from-deployer-nsg.yml
        parameters:
          deployer_env: "UNIT"
  - job: deleteSAPLandscape
    dependsOn: createSAPLandscape
    condition: or(succeededOrFailed(), always())
    steps:
      - template: templates/util/prepare-agent.yml
      - template: templates/util/collect-deployer-info.yml
        parameters:
          deployer_env: "UNIT"
      - template: templates/util/add-agent-to-deployer-nsg.yml
        parameters:
          deployer_env: "UNIT"
      - template: templates/saplandscape/delete-saplandscape-steps.yml
        parameters:
          branch_name: $(sourceBranchName)
          deployer_env: "UNIT"
          saplandscape_env: "$(Build.BuildId)"
      - template: templates/util/remove-agent-from-deployer-nsg.yml
        parameters:
          deployer_env: "UNIT"
